# Generated by Django 2.1.7 on 2019-03-17 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VictimDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('latitude', models.DecimalField(decimal_places=2, max_digits=15)),
                ('longitude', models.DecimalField(decimal_places=2, max_digits=15)),
                ('phoneno', models.IntegerField()),
                ('image', models.FileField(upload_to='media')),
            ],
        ),
    ]
