# Generated by Django 2.1.7 on 2019-03-18 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Drone', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='victimdetails',
            options={'verbose_name': 'VictimDetails', 'verbose_name_plural': 'VictimDetails'},
        ),
        migrations.AlterField(
            model_name='victimdetails',
            name='image',
            field=models.FileField(blank=True, upload_to='media'),
        ),
        migrations.AlterField(
            model_name='victimdetails',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15),
        ),
        migrations.AlterField(
            model_name='victimdetails',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15),
        ),
    ]
