# Generated by Django 2.1.7 on 2019-03-18 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Drone', '0002_auto_20190318_1338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='victimdetails',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='media'),
        ),
        migrations.AlterField(
            model_name='victimdetails',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='victimdetails',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
    ]
