# Generated by Django 2.1.7 on 2019-03-18 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Drone', '0003_auto_20190318_1349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='victimdetails',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='victimdetails',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
